version: "3.9"

services:
  backend:
    container_name: tianyu-website-backend
    image: ghcr.io/tianyu-00/tianyu-website-backend:latest
    ports:
      - "34443:9090"
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV}
      - PGDATABASE=${PGDATABASE}
      - DATABASE_URL=${DATABASE_URL}
      - PORT=9090
    networks:
      - tianyu-website-network

  frontend:
    container_name: tianyu-website-frontend
    image: ghcr.io/tianyu-00/tianyu-website-frontend:latest
    ports:
      - "34442:80"
    restart: unless-stopped
    networks:
      - tianyu-website-network

networks:
  tianyu-website-network:
    driver: bridge
