version: "3.8"

services:
  app:
    build: .
    container_name: express_app
    environment:
      NODE_ENV: production
      PGDATABASE: ${PGDATABASE}
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "9090:9090"
    volumes:
      - .:/usr/src/app
